import js from '@eslint/js';
import globals from 'globals';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.node,
                ...globals.mocha
            }
        },
        rules: {
            // Possible Problems
            'array-callback-return': 'error',
            'no-await-in-loop': 'error',
            'no-constant-binary-expression': 'error',
            'no-constructor-return': 'error',
            'no-duplicate-imports': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-promise-executor-return': 'error',
            'no-self-compare': 'error',
            'no-template-curly-in-string': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unreachable-loop': 'error',
            'no-unused-private-class-members': 'error',
            'no-use-before-define': 'error',
            'require-atomic-updates': 'error',

            // Suggestions
            'accessor-pairs': 'error',
            'arrow-body-style': ['error', 'always'],
            'block-scoped-var': 'error',
            'camelcase': 'error',
            'consistent-return': 'error',
            'consistent-this': ['error', 'self'],
            'curly': ['error', 'all'],
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            'eqeqeq': ['error', 'always'],
            'func-name-matching': 'error',
            'func-names': ['error', 'always'],
            'func-style': ['error', 'declaration'],
            'grouped-accessor-pairs': ['error', 'getBeforeSet'],
            'guard-for-in': 'error',
            'id-denylist': 'off',
            'id-length': ['error', { 'min': 2, 'exceptions': ['i', 'j', 'k', 'x', 'y', 'z', 'a', 'b', 'p', 'w', 'e', 'r'] }],
            'max-classes-per-file': ['error', 1],
            'max-depth': ['error', 3],
            'max-lines': ['error', { 'max': 200, 'skipBlankLines': true, 'skipComments': true }],
            'max-lines-per-function': ['error', { 'max': 50, 'skipBlankLines': true, 'skipComments': true }],
            'max-nested-callbacks': ['error', 3],
            'max-params': ['error', 5],
            'max-statements': ['error', 15],
            'new-cap': 'error',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'error',
            'no-caller': 'error',
            'no-console': 'error',
            'no-continue': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'error',
            'no-empty-function': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'error',
            'no-implied-eval': 'error',
            'no-inline-comments': 'error',
            'no-invalid-this': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': 'off',
            'no-multi-assign': 'error',
            'no-multi-str': 'error',
            'no-negated-condition': 'error',
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-object-constructor': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'error',
            'no-plusplus': 'error',
            'no-proto': 'error',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-sequences': 'error',
            'no-shadow': 'error',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-undefined': 'off',
            'no-underscore-dangle': 'error',
            'no-unneeded-ternary': 'error',
            'no-unused-expressions': 'error',
            'no-useless-call': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-constructor': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'off',
            'no-warning-comments': 'warn',
            'object-shorthand': ['error', 'always'],
            'one-var': ['error', 'never'],
            'operator-assignment': ['error', 'always'],
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
            'prefer-destructuring': ['error', { 'array': false, 'object': true }],
            'prefer-exponentiation-operator': 'error',
            'prefer-named-capture-group': 'error',
            'prefer-numeric-literals': 'error',
            'prefer-object-has-own': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            'radix': 'error',
            'require-await': 'error',
            'require-unicode-regexp': 'error',
            'sort-imports': ['error', { 'ignoreCase': true, 'ignoreDeclarationSort': true }],
            'sort-keys': 'off',
            'sort-vars': 'error',
            'strict': ['error', 'never'],
            'symbol-description': 'error',
            'vars-on-top': 'error',
            'yoda': 'error',

            // Layout & Formatting
            'line-comment-position': ['error', { 'position': 'above' }],
            'unicode-bom': ['error', 'never']
        }
    },
    {
        files: ['src/modbusSource.js'],
        rules: {
            'max-params': ['error', 8],
            'max-lines-per-function': ['error', { 'max': 60, 'skipBlankLines': true, 'skipComments': true }],
            'max-statements': ['error', 20]
        }
    },
    {
        files: ['test/**/*.js'],
        rules: {
            'max-lines': 'off',
            'max-lines-per-function': 'off',
            'max-statements': 'off',
            'max-nested-callbacks': ['error', 5],
            'prefer-arrow-callback': 'off',
            'func-names': 'off',
            'id-denylist': 'off',
            'no-undefined': 'off',
            'no-empty-function': 'off',
            'func-style': 'off',
            'no-invalid-this': 'off',
            'no-await-in-loop': 'off',
            'camelcase': ['error', { 'properties': 'never' }],
            'id-length': ['error', { 'min': 2, 'exceptions': ['i', 'j', 'k', 'x', 'y', 'z', 'a', 'b', 'p', 'w', 'e', 'r', 'c', 't', 'v', '_'] }]
        }
    }
];
